// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lifndrkyofhmhdkpdpcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZm5kcmt5b2ZobWhka3BkcGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTUwODgsImV4cCI6MjA2NTU5MTA4OH0.i_fETq3rEwB4t4NVCGh3q6fLS4c14LqPfeXmaLtiRk4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);